### ISSUE TITLE
Image for Readme

### ISSUE THREAD

**Issue by killix** [broidhq/broid-feedback#1]
![broid-logo](https://cloud.githubusercontent.com/assets/1795343/21583108/a17bbc6a-d03f-11e6-8f8b-c0b0ab262969.png)

**Comment by killix** [comment]
![broid_logo_big](https://cloud.githubusercontent.com/assets/1795343/21964643/0296efc2-db1e-11e6-9f9b-83e586b730a5.png)

**Comment by broidy** [comment]
![logo](https://cloud.githubusercontent.com/assets/22947293/22173058/6a003356-df85-11e6-9940-da4fd1fa1f6d.png)

**Comment by broidy** [comment]
![logo](https://cloud.githubusercontent.com/assets/22947293/22179714/e63879ca-e029-11e6-9234-d317a0ae57a2.png)
